Added new models for Tag and TagQuestion. Expanded Question model.
maleksandar/questionary pull request #3
Opened 2016-12-27 16:51 UTC by preocanin

Read the associate functions in tag.js and question.js.

2016-12-27 20:17 UTC, maleksandar requested changes

2016-12-27 20:17 UTC, maleksandar commented on models/question.js
> +                Question.belongsToMany(models.Tag, {
Mislim da je bolje `Question.hasMany` u ovom slučaju, jer to više semantički odgovara.
Takođe, ako ovako prošireni modeli rade, i prave odgovarajuće kolone i tabele u bazi, odkomentariši kod.
Repozitorijum ne bi trebao da sadrži komentarisan kod.

2016-12-27 20:17 UTC, maleksandar commented on models/tag.js
> +};
dodaj po praznu liniju na kraj fajla, jer se git buni zbog ovakvih stvari.

2016-12-27 23:21 UTC, preocanin commented on models/question.js
> +                Question.belongsToMany(models.Tag, {
Mislim da je bolje koristiti belongsToMany posto ce u tom slucaju Tag imati metode nad objetkima getQuestions, setQuestions, addQuestion i addQuestions, a Question isto to samo umesto Questions/Question ce imati Tags/Tag. Tako pise u dokumentaciji za hasMany nista nisu nveli.

2016-12-28 14:01 UTC, maleksandar approved these changes

2016-12-28 14:02 UTC, merged